"""Deterministic proactive-maintenance suggestions from verified memory."""

from __future__ import annotations

import hashlib
from collections import defaultdict
from collections.abc import Iterable, Sequence
from datetime import datetime, timezone
from enum import Enum
from statistics import median
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from steward.domain.enums import AutonomyLevel, Category
from steward.domain.models import UtcDatetime
from steward.memory.records import CaseRecord
from steward.policy import PolicyEngine

__all__ = [
    "MaintenanceSuggestion",
    "ProactiveMaintenanceEngine",
    "ProactiveRule",
    "ProactiveRuleKind",
    "SuggestionStatus",
]


class ProactiveRuleKind(str, Enum):
    RECURRENCE = "recurrence"
    CALENDAR = "calendar"


class SuggestionStatus(str, Enum):
    SUGGESTED = "suggested"
    ACCEPTED = "accepted"
    DISMISSED = "dismissed"
    EXPIRED = "expired"


class _Model(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, use_enum_values=False)


class ProactiveRule(_Model):
    """Data rule supplied by a category playbook, never generated by a model."""

    rule_id: str = Field(min_length=1)
    category: Category
    kind: ProactiveRuleKind
    title: str = Field(min_length=1, max_length=200)
    asset_id: str | None = None
    lead_days: int = Field(default=30, ge=0, le=366)
    horizon_days: int = Field(default=120, gt=0, le=730)
    min_verified_cases: int = Field(default=2, ge=1, le=20)
    calendar_month: int | None = Field(default=None, ge=1, le=12)
    calendar_day: int | None = Field(default=None, ge=1, le=31)

    @model_validator(mode="after")
    def _shape_matches_kind(self) -> ProactiveRule:
        if self.kind is ProactiveRuleKind.CALENDAR:
            if self.calendar_month is None or self.calendar_day is None:
                raise ValueError("calendar rule needs a month and day")
        elif self.calendar_month is not None or self.calendar_day is not None:
            raise ValueError("recurrence rule cannot carry calendar fields")
        return self


class MaintenanceSuggestion(_Model):
    suggestion_id: str
    rule_id: str
    kind: ProactiveRuleKind
    category: Category
    asset_id: str | None
    title: str
    reason: str
    suggested_at: UtcDatetime
    due_at: UtcDatetime
    source_ids: tuple[str, ...]
    source_case_ids: tuple[str, ...]
    policy_level: AutonomyLevel
    policy_rule_id: str
    status: SuggestionStatus = SuggestionStatus.SUGGESTED
    decided_by: str | None = None
    decided_at: UtcDatetime | None = None
    vendor_contact_allowed: Literal[False] = False
    requires_human_review: Literal[True] = True

    @model_validator(mode="after")
    def _sources_are_traceable(self) -> MaintenanceSuggestion:
        if self.rule_id not in self.source_ids:
            raise ValueError("suggestion sources must include its deterministic rule id")
        return self

    @model_validator(mode="after")
    def _decision_is_traceable(self) -> MaintenanceSuggestion:
        decided = self.status in (SuggestionStatus.ACCEPTED, SuggestionStatus.DISMISSED)
        if decided:
            if not (self.decided_by and self.decided_by.strip()):
                raise ValueError("an accepted or dismissed suggestion needs a decision source")
            if self.decided_at is None:
                raise ValueError("an accepted or dismissed suggestion needs a decision time")
        elif self.status is SuggestionStatus.SUGGESTED and (
            self.decided_by is not None or self.decided_at is not None
        ):
            raise ValueError("a suggested suggestion cannot carry a decision")
        return self


class ProactiveMaintenanceEngine:
    """Suggest maintenance without opening a case or contacting a vendor."""

    __slots__ = ("_policy", "_rules")

    def __init__(self, *, policy: PolicyEngine, rules: Sequence[ProactiveRule]) -> None:
        ids = [rule.rule_id for rule in rules]
        if len(ids) != len(set(ids)):
            raise ValueError("proactive rule ids must be unique")
        self._policy = policy
        self._rules = tuple(rules)

    def suggest(
        self,
        records: Iterable[CaseRecord],
        *,
        as_of: datetime,
    ) -> tuple[MaintenanceSuggestion, ...]:
        if as_of.tzinfo is None:
            raise ValueError("proactive as_of must be timezone-aware")
        now = as_of.astimezone(timezone.utc)
        verified = tuple(
            record for record in records if record.outcome_verified and record.closed_at <= now
        )
        by_category_asset: dict[tuple[Category, str | None], list[CaseRecord]] = defaultdict(list)
        for record in verified:
            by_category_asset[(record.category, record.asset_id)].append(record)

        suggestions: list[MaintenanceSuggestion] = []
        for rule in self._rules:
            if rule.kind is ProactiveRuleKind.RECURRENCE:
                suggestions.extend(
                    self._recurrence_suggestions(
                        rule=rule,
                        groups=by_category_asset,
                        now=now,
                    )
                )
            else:
                suggestion = self._calendar_suggestion(
                    rule=rule,
                    groups=by_category_asset,
                    now=now,
                )
                if suggestion is not None:
                    suggestions.append(suggestion)
        return tuple(
            sorted(
                suggestions,
                key=lambda item: (
                    item.due_at,
                    item.category.value,
                    item.asset_id or "",
                    item.rule_id,
                ),
            )
        )

    def _recurrence_suggestions(
        self,
        *,
        rule: ProactiveRule,
        groups: dict[tuple[Category, str | None], list[CaseRecord]],
        now: datetime,
    ) -> list[MaintenanceSuggestion]:
        suggestions: list[MaintenanceSuggestion] = []
        for (category, asset_id), group in groups.items():
            if category is not rule.category:
                continue
            if rule.asset_id is not None and asset_id != rule.asset_id:
                continue
            records = sorted(
                (
                    record
                    for record in group
                    if not record.is_planned_maintenance and not record.is_recall
                ),
                key=lambda record: (record.opened_at, record.case_id),
            )
            if len(records) < rule.min_verified_cases:
                continue
            window = records[-rule.min_verified_cases :]
            intervals = [
                (later.opened_at - earlier.opened_at).total_seconds() / 86400.0
                for earlier, later in zip(window, window[1:], strict=False)
            ]
            if not intervals:
                continue
            interval_days = max(int(round(median(intervals))), 1)
            due_at = window[-1].opened_at + _days(interval_days)
            if not _within_window(due_at, now=now, rule=rule):
                continue
            source_case_ids = tuple(record.case_id for record in window)
            suggestions.append(
                self._suggestion(
                    rule=rule,
                    asset_id=asset_id,
                    now=now,
                    due_at=due_at,
                    source_case_ids=source_case_ids,
                    reason=(
                        f"{len(window)} verified cases recurred about every "
                        f"{interval_days} day(s); the next interval points to "
                        f"{due_at.date().isoformat()}."
                    ),
                )
            )
        return suggestions

    def _calendar_suggestion(
        self,
        *,
        rule: ProactiveRule,
        groups: dict[tuple[Category, str | None], list[CaseRecord]],
        now: datetime,
    ) -> MaintenanceSuggestion | None:
        assert rule.calendar_month is not None  # noqa: S101 - model validator
        assert rule.calendar_day is not None  # noqa: S101 - model validator
        try:
            due_at = datetime(
                now.year,
                rule.calendar_month,
                rule.calendar_day,
                9,
                tzinfo=timezone.utc,
            )
        except ValueError as exc:
            raise ValueError(f"invalid calendar date in rule {rule.rule_id}") from exc
        if due_at < now - _days(rule.lead_days):
            due_at = due_at.replace(year=due_at.year + 1)
        if not _within_window(due_at, now=now, rule=rule):
            return None

        candidates = sorted(
            (
                record
                for (category, asset_id), records in groups.items()
                if category is rule.category
                and (rule.asset_id is None or asset_id == rule.asset_id)
                for record in records
            ),
            key=lambda record: (record.closed_at, record.case_id),
        )
        source_case_ids = tuple(record.case_id for record in candidates[-3:])
        return self._suggestion(
            rule=rule,
            asset_id=rule.asset_id,
            now=now,
            due_at=due_at,
            source_case_ids=source_case_ids,
            reason=(
                f"Playbook rule {rule.rule_id} schedules this review for "
                f"{due_at.date().isoformat()}."
            ),
        )

    def _suggestion(
        self,
        *,
        rule: ProactiveRule,
        asset_id: str | None,
        now: datetime,
        due_at: datetime,
        source_case_ids: tuple[str, ...],
        reason: str,
    ) -> MaintenanceSuggestion:
        decision = self._policy.evaluate_intake(
            category=rule.category,
            triage_confidence=1.0,
        )
        source_ids = (rule.rule_id, *source_case_ids)
        identity = "|".join(
            (
                rule.rule_id,
                asset_id or "category",
                due_at.date().isoformat(),
            )
        )
        suggestion_id = "suggestion-" + hashlib.sha256(identity.encode("utf-8")).hexdigest()[:20]
        return MaintenanceSuggestion(
            suggestion_id=suggestion_id,
            rule_id=rule.rule_id,
            kind=rule.kind,
            category=rule.category,
            asset_id=asset_id,
            title=rule.title,
            reason=reason,
            suggested_at=now,
            due_at=due_at,
            source_ids=source_ids,
            source_case_ids=source_case_ids,
            policy_level=decision.level,
            policy_rule_id=decision.rule_id,
            vendor_contact_allowed=False,
            requires_human_review=True,
        )


def _within_window(due_at: datetime, *, now: datetime, rule: ProactiveRule) -> bool:
    return now - _days(rule.lead_days) <= due_at <= now + _days(rule.horizon_days)


def _days(value: int):
    from datetime import timedelta

    return timedelta(days=value)
