"""Run the same product acceptance tests against an isolated PostgreSQL schema."""

import os
from uuid import uuid4

import pytest


@pytest.fixture
def postgres_environment(monkeypatch):
    dsn = os.getenv("STEWARD_TEST_POSTGRES_DSN")
    if not dsn:
        pytest.skip("STEWARD_TEST_POSTGRES_DSN is required for PostgreSQL integration")
    import psycopg
    from psycopg import sql
    from psycopg.conninfo import make_conninfo

    schema = "test_" + uuid4().hex
    with psycopg.connect(dsn, autocommit=True) as connection:
        connection.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
    monkeypatch.setenv(
        "STEWARD_DATABASE_URL", make_conninfo(dsn, options=f"-csearch_path={schema}")
    )
    yield
    # Only the schema generated by this fixture is removed.
    with psycopg.connect(dsn, autocommit=True) as connection:
        connection.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema)))


@pytest.mark.parametrize(
    "scenario",
    [
        "maintenance",
        "rejected",
        "community",
        "concurrency",
        "leases",
        "community_procurement",
        "late_unsent",
        "late_delivered",
        "clarification",
        "appointment",
        "rounds",
        "revision",
        "atomic_answer",
        "mail_queue",
        "late_appointment_receipt",
        "assignment_revision",
    ],
)
def test_product_on_postgres(postgres_environment, tmp_path, scenario):
    if scenario in (
        "clarification",
        "appointment",
        "rounds",
        "revision",
        "atomic_answer",
        "mail_queue",
        "late_appointment_receipt",
        "assignment_revision",
    ):
        import test_four_stage_continuity as continuity

        {
            "clarification": continuity.test_clarification_is_personal_reassessed_and_restart_safe,
            "appointment": continuity.test_delivered_order_waits_for_sourced_appointment,
            "rounds": continuity.test_meeting_retry_rounds_do_not_reuse_old_answers_and_stop_at_two,
            "revision": continuity.test_material_decision_revision_preserves_confirmed_decision,
            "atomic_answer": (
                continuity.test_atomic_clarification_answer_rolls_back_if_job_write_fails
            ),
            "mail_queue": continuity.test_ses_ack_does_not_wait_for_model,
            "late_appointment_receipt": (
                continuity.test_older_appointment_receipt_cannot_replace_current_date
            ),
            "assignment_revision": (
                continuity.test_assignment_revisions_keep_previous_owner_and_follow_new_due
            ),
        }[scenario](tmp_path)
        return
    if scenario in ("late_unsent", "late_delivered"):
        from test_product_boundaries import (
            test_late_quote_revises_only_an_order_that_never_started_dispatch,
        )

        test_late_quote_revises_only_an_order_that_never_started_dispatch(
            tmp_path, scenario == "late_delivered"
        )
        return
    if scenario in ("concurrency", "leases"):
        import test_workflow_jobs as workflows

        from steward.store.postgres import PostgresOperationalStore

        with pytest.MonkeyPatch.context() as context:
            context.setattr(
                workflows,
                "SqliteOperationalStore",
                lambda *_: PostgresOperationalStore(os.environ["STEWARD_DATABASE_URL"]),
            )
            {
                "concurrency": workflows.test_concurrent_reservations_cannot_overspend,
                "leases": workflows.test_claim_fencing_and_exhaustion_creates_human_task,
            }[scenario](tmp_path)
        return
    from test_community_product import (
        test_community_events_reach_verified_memory_without_manual_service_calls,
        test_confirmed_community_action_reaches_linked_verified_maintenance,
    )
    from test_product_lifecycle import (
        test_rejected_completion_does_not_teach_success,
        test_worker_to_human_verification_writes_memory_atomically,
    )

    {
        "maintenance": test_worker_to_human_verification_writes_memory_atomically,
        "rejected": test_rejected_completion_does_not_teach_success,
        "community": test_community_events_reach_verified_memory_without_manual_service_calls,
        "community_procurement": (
            test_confirmed_community_action_reaches_linked_verified_maintenance
        ),
    }[scenario](tmp_path)
